As a result of r21308, if we are building with "--disable-mpi-io " make sure that MPI_MAX_DATAREP_STRING is defined in mpi.h
MTT caught builds failing with the following error which flagged the problem:
{{{
param.cc:802: error: ‘MPI_MAX_DATAREP_STRING’ was not declared in this scope
}}}



git-svn-id: http://svn.open-mpi.org/svn/ompi/trunk@21337 63e3feb5-37d5-0310-a306-e8a459e722fe